In [ ]:
pd.__version__

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.3.1'

In [ ]:
import numpy as np

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3]

np.int64(4)

In [ ]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
np.zeros(10)

np.zeros((3, 5))


In [1]:
np.zeros(10)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [8]:
n[0, 1]

np.int64(2)

In [9]:
np.random.rand(5, 2)

array([[0.97020574, 0.38840865],
       [0.46673106, 0.33544101],
       [0.01199897, 0.18886006],
       [0.60133735, 0.97901198],
       [0.93425444, 0.11550977]])

In [13]:
np.random.seed(2)
np.random.randint(low='1', high='20', size=(4, 2))

array([[ 9, 16],
       [14,  9],
       [12, 19],
       [12,  9]])

In [14]:
a = np.arange(5)

In [15]:
a

array([0, 1, 2, 3, 4])

In [16]:
a + 1

array([1, 2, 3, 4, 5])

In [17]:
a * 200

array([  0, 200, 400, 600, 800])

In [18]:
a

array([0, 1, 2, 3, 4])

In [19]:
a >= 2

array([False, False,  True,  True,  True])

In [1]:
import numpy as np

In [1]:
import numpy as np

In [15]:
u = np.array([2, 4, 5, 6])

In [16]:
v = np.array([1, 0, 0, 2])

In [19]:
u.dot(v)

np.int64(14)

In [17]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result += u[i] * v[i]
    return result

In [18]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [20]:
U = np.array ([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [ ]:
v = np.array([1, 0, 0, 2])

In [21]:
U.shape

(3, 4)

In [23]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    vector_result = np.zeros(num_rows)

    for i in range(num_rows):
        vector_result [i] = vector_vector_multiplication(U[i], v)
    return vector_result

In [24]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [25]:
U = np.array ([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [41]:
V = np.array ([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [48]:
U.shape[1]

4

In [49]:
V.shape[0]

4

In [44]:
U[1][2]

np.int64(1)

In [45]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
V[:, 2]

array([2., 1., 1., 0.])

In [54]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    matrix_result = np.zeros((num_rows, num_cols))

    for i in range(num_rows):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        matrix_result[:, i] = Uvi
    return matrix_result

In [55]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [56]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [57]:
import pandas as pd

In [58]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [59]:
df = pd.DataFrame(data, columns=columns)

In [60]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [61]:
df.Model

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: object

In [62]:
df[["Model", "Year", "Engine HP"]]

Model  Year  Engine HP
0    Stanza  1991      138.0
1    Sonata  2017        NaN
2     Elise  2010      218.0
3    Acadia  2017      194.0
4  Frontier  2017      261.0

In [63]:
df["Engine HP"] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [64]:
df['Engine HP'].fillna(100.0)

0    138.0
1    100.0
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [67]:
df[['Year', 'Engine HP']].values

array([[1991.,  138.],
       [2017.,   nan],
       [2010.,  218.],
       [2017.,  194.],
       [2017.,  261.]])